# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='delivery_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dostawa'),
        ),
    ]
