# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_b2b'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='b2b',
            field=models.BooleanField(default=True),
        ),
    ]
