# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_b2b'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Koszt dostawy'),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Czas dostawy'),
        ),
    ]
