# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Producent')),
                ('model', models.CharField(db_index=True, max_length=200)),
                ('slug', models.CharField(db_index=True, max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nazwa')),
                ('slug', models.CharField(db_index=True, max_length=200, verbose_name='SAP')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('sap', models.CharField(max_length=200, unique=True, verbose_name='SAP')),
                ('ean', models.CharField(blank=True, max_length=200, null=True, verbose_name='EAN')),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Producent')),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Model bieżnika')),
                ('size', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rozmiar')),
                ('speed_index', models.CharField(blank=True, max_length=200, null=True, verbose_name='Indeks Prędkości')),
                ('load_index', models.CharField(blank=True, max_length=200, null=True, verbose_name='Indeks Nośności')),
                ('rolling_resistance', models.CharField(blank=True, max_length=200, null=True, verbose_name='Opor Toczenia')),
                ('adhesion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Przyczepnosc na mokrym')),
                ('noise', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hałas [db]')),
                ('dot', models.CharField(blank=True, max_length=5, null=True, verbose_name='DOT')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Netto [PL]')),
                ('price_ue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Netto [UE]')),
                ('stock', models.PositiveIntegerField(verbose_name='Stan')),
                ('available', models.BooleanField(default=True, verbose_name='Dostępne')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Aktualizowano')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_image', to='shop.Images', verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'ordering': ('name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='images',
            index_together=set([('id', 'slug')]),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'slug')]),
        ),
    ]
