# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_search_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_marking',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dodatkowe oznaczenie'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('', ''), ('Lato', 'Lato'), ('Zima', 'Zima'), ('Całoroczna', 'Całoroczna')], default='', max_length=50, verbose_name='Sezon'),
        ),
        migrations.AddField(
            model_name='product',
            name='typ',
            field=models.CharField(choices=[('Osobowe', 'Osobowe'), ('4x4', '4x4'), ('SUV', 'SUV'), ('Bus', 'Bus'), ('Ciężarowe', 'Ciężarowe'), ('Motocyklowe', 'Motocyklowe')], default='Osobowe', max_length=50, verbose_name='Sezon'),
        ),
    ]
