# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171009_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='typ',
            field=models.CharField(choices=[('', ''), ('Osobowe', 'Osobowe'), ('4x4', '4x4'), ('SUV', 'SUV'), ('Bus', 'Bus'), ('Ciężarowe', 'Ciężarowe'), ('Motocyklowe', 'Motocyklowe')], default='', max_length=50, verbose_name='Sezon'),
        ),
    ]
