# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20171009_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Netto [PL]'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_ue',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Netto [UE]'),
        ),
    ]
