# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20171009_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SEZON'),
        ),
        migrations.AlterField(
            model_name='product',
            name='typ',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TYP'),
        ),
    ]
