# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_odbior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='odbior',
        ),
    ]
