# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_odbior'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kurier',
            field=models.BooleanField(default=False, verbose_name='Wysyłka kurierem'),
        ),
    ]
